### ISSUE TITLE
conflicting brand

### ISSUE THREAD

**Issue by the-phoenix** [praveenjuge/tailwindcss-brand-colors#2]
https://github.com/praveenjuge/tailwindcss-brand-colors/blob/1f0b90d44f78b6776c29416f01656036b6f54119/index.js#L50
https://github.com/praveenjuge/tailwindcss-brand-colors/blob/1f0b90d44f78b6776c29416f01656036b6f54119/index.js#L46

**Comment by praveenjuge** [comment]
Thanks for raising an issue. Fixed in release v0.3.1 👍
